"""initial schema

Revision ID: a9ee499418b4
Revises: 
Create Date: 2026-02-08 19:49:59.099498
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9ee499418b4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amenities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('builders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('website_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('localities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'city_id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('builder_id', sa.Integer(), nullable=False),
    sa.Column('locality_id', sa.Integer(), nullable=True),
    sa.Column('location_text', sa.String(length=500), nullable=True),
    sa.Column('configurations', sa.Text(), nullable=False),
    sa.Column('bhk_options', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('total_units', sa.Integer(), nullable=True),
    sa.Column('towers', sa.Integer(), nullable=True),
    sa.Column('floors', sa.String(length=50), nullable=True),
    sa.Column('area_text', sa.String(length=100), nullable=True),
    sa.Column('area_acres', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('unit_sizes_text', sa.String(length=200), nullable=True),
    sa.Column('unit_size_min', sa.Integer(), nullable=True),
    sa.Column('unit_size_max', sa.Integer(), nullable=True),
    sa.Column('units_per_acre', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('price_text', sa.String(length=200), nullable=True),
    sa.Column('price_min_cr', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_max_cr', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('possession_text', sa.String(length=200), nullable=True),
    sa.Column('possession_date', sa.Date(), nullable=True),
    sa.Column('possession_year', sa.Integer(), nullable=True),
    sa.Column('rera_number', sa.String(length=100), nullable=True),
    sa.Column('rera_registered', sa.Boolean(), nullable=False),
    sa.Column('clubhouse_text', sa.String(length=200), nullable=True),
    sa.Column('clubhouse_sqft', sa.Integer(), nullable=True),
    sa.Column('open_space_text', sa.String(length=100), nullable=True),
    sa.Column('open_space_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('lng', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('standout_features', sa.Text(), nullable=True),
    sa.Column('location_highlights', sa.Text(), nullable=True),
    sa.Column('builder_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['builder_id'], ['builders.id'], ),
    sa.ForeignKeyConstraint(['locality_id'], ['localities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('project_amenities',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('amenity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['amenity_id'], ['amenities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'amenity_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_amenities')
    op.drop_table('projects')
    op.drop_table('localities')
    op.drop_table('cities')
    op.drop_table('builders')
    op.drop_table('amenities')
    # ### end Alembic commands ###
